### PR TITLE
feat: add linear hall position sensor driver

### PR DESCRIPTION
**Pull request by nanoparticle**
Not entirely sure where the driver files should go, or how exactly the includes are structured, but the basic functionality is here and superficially tested.

### CODE REVIEW

**Comment by runger1101001** [comment]
Hey @nanoparticle, how do you feel about this? There was a SimpleFOC release today, including the changes to the init() code that you wanted... how about this code? is it ready to merge to the drivers?

**Comment by nanoparticle** [comment]
I haven't had time to do any real testing on this code beyond seeing if it is a feasible method of sensing. How much testing should it go through before being merged?

**Comment by runger1101001** [comment]
Hey @nanoparticle  do we want to merge this? It's still in draft status...

For the drivers repository, the bar is not set very high - you don't have to test much. If it runs in some of your own setups it is enough... each folder in the drivers repository has its own README, so we can add a warning note for users to let them know it isn't tested much...

**Comment by runger1101001** [comment]
Also, did you see this one: https://github.com/simplefoc/Arduino-FOC/pull/197

It's a similar implementation, I think...

**Comment by dekutree64** [comment]
Upon further investigation, it looks like ADC configuration is a major problem for this sensor approach. As it is, I'm getting about 250 microseconds per analogRead on STM32G031, which is too slow for real world use. Current sense apparently requires an elaborate HAL configuration sequence for every supported platform to get good ADC performance, and separate ones for each STM32 series. That would be a maintenance nightmare to add that many files just for this one sensor. What to do?

**Comment by runger1101001** [comment]
Hey @dekutree64 , you're absolutely right, and we're keenly aware of this problem. The ultimate plan looks like this:

- the ADC drivers for the different hardwares will be refactored and abstracted by something called "ADCEngine". ADCEngine will have different capability levels on the different hardwares. On simpler hardwares it may only support the inline current sensing of one motor. But on complex hardware (like STM32, Renesas) the goal is to make it support multiple motors, multiple ADCs, current sensing, voltage sensing and other ADC use in parallel
- So in future it should be possible for the LinearHallSensor to request some ADC channels from the ADCEngine, and either get them or get an err - not supported. Those ADC channels would be faster than using analogRead() so your use-case should be possible.
- There's lots of other use cases like VBUS sensing, OC protection, Voltage sense, etc which would also need this functionality

**Comment by XieMaster** [comment]
Yes, ADC sampling is too slow, so this linear Hall angle feedback method is more suitable for use in lower-speed projects such as pan/tilts.
Only a 1-pole pair magnet and two linear Halls need to be installed to replace expensive magnetic encoders.

**Comment by runger1101001** [comment]
I have just merged deku's implementation to the drivers repository dev branch, it will be part of the next release... do you all agree we can close this PR (which is still in draft status) in favor of the merged implementation?

**Comment by nanoparticle** [comment]
Thanks so much to everyone for pulling this over the finish line 👍

**Pull request closed without merging**
